version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Pre-Building ..."
      - sam --version
  build:
    commands:
      - echo "Building ..."
      - cd sam-app
      - sam build
      - sam package --s3-bucket ${S3_BUCKET} --output-template-file packaged-template.ym --kms-key-id ${KMS_KEY_ID}
artifacts:
  type: zip
  files:
    - sam-app/packaged-template.yml
