version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Pre-Building ..."
      - sam --version
  build:
    commands:
      - echo "Building ..."
      - sam build
      - sam package --s3-bucket $BACKET_NAME --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
